In [10]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt



# Creating 3D model

In [11]:
np.random.seed(4)
m = 60
w1, w2 = 0.1, 0.3
noise = 0.1
angles = np.random.rand(m) * 3 * np.pi / 2 - 0.5
X = np.empty((m, 3))
X[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise * np.random.randn(m) / 2
X[:, 1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) / 2
X[:, 2] = X[:, 0] * w1 + X[:, 1] * w2 + noise * np.random.randn(m)

# PCA using SVD decomposition

In [12]:
X_centered = X - X.mean(axis=0)
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt.T[:, 0]
c2 = Vt.T[:, 1]

In [13]:
m, n = X.shape
S = np.zeros(X_centered.shape)
S[:n, :n] = np.diag(s)

In [14]:
np.allclose(X_centered, U.dot(S).dot(Vt))

True

In [15]:
W2 = Vt.T[:, :2]
X2D = X_centered.dot(W2)

In [16]:
X2D_using_svd = X2D

In [17]:
X2D_using_svd[:5]

array([[-1.26203346, -0.42067648],
       [ 0.08001485,  0.35272239],
       [-1.17545763, -0.36085729],
       [-0.89305601,  0.30862856],
       [-0.73016287,  0.25404049]])

In [18]:
X[:5]

array([[-1.01570027, -0.55091331, -0.26132626],
       [-0.00771675,  0.59958572,  0.03507755],
       [-0.95317135, -0.46453691, -0.24920288],
       [-0.92012304,  0.21009593,  0.02182381],
       [-0.76309739,  0.158261  ,  0.19152496]])

# Using Scikit_learn

In [19]:
from sklearn.decomposition import PCA

In [37]:
pca = PCA(n_components=2)
X2D = pca.fit_transform(X)

In [38]:
pca.components_

array([[-0.93636116, -0.29854881, -0.18465208],
       [ 0.34027485, -0.90119108, -0.2684542 ]])

In [39]:
pca.components_.T

array([[-0.93636116,  0.34027485],
       [-0.29854881, -0.90119108],
       [-0.18465208, -0.2684542 ]])

In [40]:
pca.components_.T[:,0]

array([-0.93636116, -0.29854881, -0.18465208])

# Explained Vaqrience Ratio

In [33]:
pca.explained_variance_ratio_

array([0.84248607, 0.14631839])

In [34]:
pca.explained_variance_

array([0.77830975, 0.1351726 ])